name: Blog Posts Update

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 0시에 실행
  workflow_dispatch:

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch RSS and update README
        uses: gautamkrishnar/blog-post-workflow@v1.0.5
        with:
          rss-feed-url: 'https://velog.io/@dereck-jun/posts'  # 본인 블로그 RSS 주소
          max-posts: 5                 # 최대 5개의 글만 표시
          output-file: README.md       # 업데이트할 파일
          start-tag: '<!-- BLOG-POST-LIST:START -->'
          end-tag: '<!-- BLOG-POST-LIST:END -->'
